---
title: "Practice Midterm"
author: "Eric Jess"
date: "10/14/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, echo=FALSE}
housedir <- "C:/Users/etj3pp/Documents/SYS 4021/Data/"
sourcedir <- "C:/Users/etj3pp/Documents/SYS 4021/Source/"

set##load data
setwd(housedir)
housing = read.csv('housing.csv',sep=',',header=T)
setwd(sourcedir)
source("AccidentInput.R")

#load libraries
library(ggplot2)
library(GGally)
library(devtools) # for ggbiplot
library(ggbiplot)

```

```{r Q1 Q2, echo=FALSE}
#QUESTION 1
pricebox<-boxplot(housing$price, xlab="Price", ylab="Dollars ($)")
summary(pricebox)

#QUESTION 2
pricebox$stats
quantile(housing$price)
```
```{r}
#QUESTION 3, 4
ggpairs(housing[,c("bedrooms","baths","sqft","price")])

#QUESTION 5, 6
house.main<-lm(price~sqft+bedrooms+baths,data=housing)
summary(house.main)
```

```{r}
#QUESTION 7
house.inter<-lm(price~(sqft+bedrooms+baths)^2,data=housing)
summary(house.inter)

#QUESTION 8, 9
anova(house.main,house.inter)

#QUESTION 10, 11
summary(house.main)$adj.r.squared
summary(house.inter)$adj.r.squared

AIC(house.main) #AIC
AIC(house.inter) #AIC

AIC(house.main,k=log(nrow(housing))) #BIC
AIC(house.inter,k=log(nrow(housing))) #BIC

```
```{r}
library(MASS)
library(lindia)

#QUESTION 12, 13
gg_diagnose(house.main)

plot(house.main,which=4) #Cook's dist vs. Leverage

count(cooks.distance(house.main)>0.5)
```
```{r}
#QUESTION 14
boxcox(house.main)
L <-boxcox(house.main, plotit = F)$x[which.max(boxcox(house.main, plotit = F)$y)]
house.main.boxcox<-lm(price^L~sqft+bedrooms+baths,data=housing)

library(olsrr)
ols_test_breusch_pagan(house.main.boxcox)
```
```{r}
#QUESTION 15
lm(price~City,data=housing)
```
```{r}
#QUESTION 16
house.pca.cor <- princomp(housing[,c("price","sqft","bedrooms","baths")],cor=T)
ggbiplot(house.pca.cor)

#QUESTION 17

cumplot <- function(pca.obj, ...)
	{
		xc <- cumsum(pca.obj$sdev^2)/sum(pca.obj$sdev^2)
		barplot(xc, ylim = c(0,1), main = "Proportion of Variance", ylab = "Proportion", names.arg = 1:length(pca.obj$sdev), xlab = "Components", ...)
		xc <- as.data.frame(xc)
		setDT(xc, keep.rownames=TRUE)[]
		names(xc)[names(xc) == "rn"] <- "Component"
		names(xc)[names(xc) == "xc"] <- "Proportion"
		return(xc)
	}

cumplot(house.pca.cor)
screeplot(house.pca.cor)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
